# Generated by Django 4.1.1 on 2022-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_course_message_notice_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
